import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import ToasterProvider from "@/providers/ToasterProvider";
import Navbar from "@/components/landing/Navbar";
import getCurrentUser from "@/actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar currentUser={currentUser} />
        <ToasterProvider />
        <main className="h-full  overflow-auto">
          <div className="mx-auto max-w-screen-2xl h-full ">{children}</div>
        </main>
      </body>
    </html>
  );
}
